from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg", ".webp"}


def find_page_images(project_dir: Path) -> list[Path]:
    rendered = project_dir / "rendered"
    candidates: list[Path] = []
    if rendered.is_dir():
        candidates.extend(sorted(path for path in rendered.iterdir() if path.suffix.lower() in IMAGE_EXTENSIONS))
    if not candidates:
        candidates.extend(sorted(path for path in project_dir.glob("slide_*") if path.suffix.lower() in IMAGE_EXTENSIONS))
    if not candidates:
        for assemble_dir in sorted((project_dir / "assemble").glob("*/starter")) if (project_dir / "assemble").is_dir() else []:
            candidates.extend(sorted(path for path in assemble_dir.glob("slide_*") if path.suffix.lower() in IMAGE_EXTENSIONS))
    return candidates


def order_for(path: Path, fallback: int) -> int:
    match = re.search(r"(\d+)", path.stem)
    return int(match.group(1)) if match else fallback


def convert_deck_pro_max_project(project_dir: Path, *, run_id: str, title: str) -> dict[str, Any]:
    images = find_page_images(project_dir)
    if not images:
        raise ValueError(f"No rendered page images found in project: {project_dir}")

    pages = []
    for index, image in enumerate(images, start=1):
        order = order_for(image, index)
        page_id = f"generated_{order:02d}"
        pages.append(
            {
                "page_id": page_id,
                "order": order,
                "title": image.stem.replace("_", " ").title(),
                "source_type": "generated",
                "preview_asset": str(image.resolve()),
                "source_project": str(project_dir.resolve()),
                "narrative_role": "generated page",
                "generation_reason": "Generated by PPT Deck Pro Max.",
                "confidence": 1,
                "decision": "needs_review",
                "notes": "",
            }
        )
    pages.sort(key=lambda page: page["order"])
    return {"run_id": run_id, "title": title, "status": "draft", "pages": pages}


def main() -> None:
    parser = argparse.ArgumentParser(description="Convert PPT Deck Pro Max rendered pages into a Deck Master orchestration plan.")
    parser.add_argument("project_dir")
    parser.add_argument("--output", required=True)
    parser.add_argument("--run-id", required=True)
    parser.add_argument("--title", required=True)
    args = parser.parse_args()

    try:
        plan = convert_deck_pro_max_project(
            Path(args.project_dir).expanduser().resolve(),
            run_id=args.run_id,
            title=args.title,
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc

    output = Path(args.output).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(plan, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"run_id": plan["run_id"], "pages": len(plan["pages"]), "output": str(output)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
