"""Independent final design-prototype review. No production acceptance."""
from pathlib import Path
import hashlib, json, time
from playwright.sync_api import sync_playwright

HERE=Path(__file__).resolve().parent
SPEC=HERE.parent.parent
URL='http://127.0.0.1:8766/'
inputs={str(f.relative_to(SPEC)):hashlib.sha256(f.read_bytes()).hexdigest() for f in (SPEC/'prototype').glob('*') if f.is_file()}
(HERE/'input.json').write_text(json.dumps({'at':time.strftime('%Y-%m-%dT%H:%M:%S%z'),'files':inputs},indent=2))
result={'scope':'Independent final browser review of synthetic design prototype only','production_acceptance':False,'results':[]}
with sync_playwright() as pw:
    browser=pw.chromium.launch()
    for w,h in [(1280,800),(1440,900)]:
        context=browser.new_context(viewport={'width':w,'height':h},permissions=['clipboard-read','clipboard-write'])
        p=context.new_page();errors=[];external=[];checks=[];screens=[]
        p.on('pageerror',lambda e:errors.append(str(e)))
        p.on('request',lambda r:external.append(r.url) if not r.url.startswith(URL) else None)
        def ok(label,test):
            assert test,label
            checks.append(label)
        def go(route):p.goto(URL+'#'+route)
        def click(label):p.get_by_role('button',name=label,exact=True).click()
        def act(key):p.locator('[data-action="'+key+'"]').first.click()
        def capture(label):
            ok(label+' fits viewport',p.evaluate('document.documentElement.scrollWidth<=innerWidth'))
            path=HERE/(label+'-'+str(w)+'.png');p.screenshot(path=str(path),full_page=True);screens.append(path.name)
        go('overview');click('看 24 页原图 →')
        ok('gallery represents all 24 pages',p.locator('.slide-tile').count()==24)
        capture('gallery')
        go('page/8/prompt')
        ok('P8 prompt trace has actual generation identity','gen-008-v2' in p.inner_text('body'))
        go('style');p.locator('#style-requirement').fill('只借用第七页色板，事实与结构保留。')
        p.locator('.fine-settings > summary').first.click()
        for dim in ['type','density','lines']:p.locator('[data-dimension="'+dim+'"]').uncheck()
        click('先试第 8 页 →');first=p.evaluate('currentStyleTask().id')
        click('复制交接文本');p.wait_for_function("currentStyleTask().status==='copied'")
        copied=p.evaluate('navigator.clipboard.readText()')
        ok('handoff fixes P7 v2 reference, P8 target and color-only','固定风格参考：第 7 页原图 v2' in copied and '实际执行范围：第 8 页' in copied and '风格维度：色板\n' in copied)
        p.reload();ok('copied is not claimed running','已复制，尚未开始' in p.inner_text('body'))
        click('模拟 Host 接手');click('模拟候选返回');capture('style-candidate')
        click('保留当前');ok('keep preserves adopted version',p.evaluate("artifact(pages[7],'image').version")==2)
        click('调整要求再试');p.locator('#style-requirement').fill('减少冷蓝色，维持事实和原有布局。')
        click('保存第 8 页的新请求 →');second=p.evaluate('currentStyleTask().id')
        ok('retry has distinct identity and retains first decision',first!=second and p.evaluate('state.tasks.find(t=>t.id==='+str(first)+').status')=='kept')
        click('模拟 Host 接手');click('模拟候选返回');click('采用这个候选 · 仅第 8 页')
        ok('adopt changes only P8 image',p.evaluate("artifact(pages[7],'image').version")==3 and p.evaluate("artifact(pages[8],'image').version")==2)
        click('将余下 1 页加入待交接');p.reload();go('style');click('查看第 9 页请求')
        ninth=p.evaluate('currentStyleTask().id');go('overview');go('style')
        ok('P9 continuation reuses fixed request',p.evaluate('state.tasks.filter(t=>t.style&&t.pages[0]===9).length')==1 and p.evaluate('currentStyleTask().id')==ninth)
        go('page/8/image');click('标注与意见');p.locator('#page-note').fill('只属于第八页新版的意见')
        go('page/9/image');click('标注与意见');ok('page notes do not bleed across page',p.locator('#page-note').input_value()!='只属于第八页新版的意见')
        go('page/8/image');click('标注与意见');ok('page note returns on matching page',p.locator('#page-note').input_value()=='只属于第八页新版的意见')
        go('page/12/image');click('执行提示词');before=p.locator('#mark-surface svg').evaluate('(e)=>e.outerHTML')
        prompt=p.locator('.page-split > section').nth(1).inner_text()
        go('page/12/svg');ok('SVG defect is visually represented',p.locator('#main [data-sample-arrow="reverse"]').count()==1)
        click('标注与意见');p.locator('#page-note').fill('诊断指向处理，箭头改向右；保留其他产物。');click('保存意见')
        count=p.evaluate('state.tasks.length');click('仅重建 SVG');click('加入待交接')
        ok('one SVG request captures saved opinion',p.evaluate('state.tasks.length')==count+1 and '诊断指向处理' in p.evaluate('state.tasks[0].note'))
        svgrow=p.locator('.run-item').filter(has_text='第 12 页仅重建 SVG')
        for label in ['模拟接手','模拟返回候选','查看候选并比较']:svgrow.get_by_role('button',name=label,exact=True).click()
        capture('svg-fixed-comparison')
        ok('SVG compare binds two distinct fixed references',p.locator('#modal [data-artifact-ref="p12/svg/v2"]').count()==1 and p.locator('#modal [data-artifact-ref="p12/svg/v3"]').count()==1)
        click('采用这个样本候选');go('page/12/svg');ok('adopted SVG fixes reverse arrow',p.locator('#main [data-sample-arrow="reverse"]').count()==0)
        go('page/12/ppt');ok('downstream PPT marked outdated','上游 SVG 已变化，待更新' in p.inner_text('body'))
        go('page/12/image');ok('SVG adoption leaves original byte-equivalent',p.locator('#mark-surface svg').evaluate('(e)=>e.outerHTML')==before)
        click('执行提示词');ok('SVG adoption leaves prompt equal',p.locator('.page-split > section').nth(1).inner_text()==prompt)
        mainstate=p.evaluate('localStorage.getItem("deck-master-v3-demo")')
        p.goto(URL+'states.html#unknown');ok('state lab is explicitly synthetic','全部为模拟' in p.inner_text('.state-banner'))
        payload=p.locator('.state-grid .state-body').first.inner_text();p.locator('#later-draft').fill('之后写的独立输入不能被原请求覆盖')
        ok('unknown cannot prematurely replay',p.locator('[data-action="replay-original"]').count()==0)
        act('check-unknown');act('new-later');p.reload()
        ok('unknown retains original payload and later draft',p.locator('.state-grid .state-body').first.inner_text()==payload and p.locator('#later-draft').input_value()=='之后写的独立输入不能被原请求覆盖')
        capture('unknown-save')
        p.locator('[data-scene="conflict"]').click();fixed=p.locator('.state-grid').inner_text();act('rebase-conflict')
        p.locator('#conflict-new').fill('以双方事实整理后的新草稿');p.reload()
        ok('conflict preserves both sources while new draft persists',p.locator('.state-grid').inner_text()==fixed and p.locator('#conflict-new').input_value()=='以双方事实整理后的新草稿')
        capture('conflict')
        p.locator('[data-scene="structure"]').click();ids=p.locator('.structure-list li').evaluate_all('(es)=>es.map(e=>e.dataset.pageId)')
        p.get_by_role('button',name='下移现状分析',exact=True).focus();p.keyboard.press('Enter')
        moved=p.locator('.structure-list li').evaluate_all('(es)=>es.map(e=>e.dataset.pageId)')
        ok('keyboard reorder preserves stable identity and focus',sorted(ids)==sorted(moved) and moved[2]=='p-b2' and p.evaluate('document.activeElement.dataset.page')=='p-b2')
        for ident in ['p-b2','p-c3']:p.locator('[data-select-page="'+ident+'"]').check()
        act('request-structure');act('confirm-request-structure');ok('request does not pre-adopt structure',p.locator('.structure-list li').count()==6)
        act('return-structure');act('adopt-structure');p.keyboard.press('Escape');ok('Escape declines adoption without losing current',p.locator('.structure-list li').count()==6)
        act('adopt-structure');act('confirm-adopt-structure');ok('merge stores new page provenance',p.locator('[data-page-id="p-merged-2"]').count()==1 and '旧意见未迁移' in p.inner_text('main'))
        p.locator('#structure-mode').select_option('split');p.locator('[data-select-page="p-a1"]').check()
        act('request-structure');act('confirm-request-structure');act('return-structure');act('adopt-structure');act('confirm-adopt-structure')
        ok('split creates two source-linked identities',p.locator('[data-page-id="p-split-3-1"]').count()==1 and p.locator('[data-page-id="p-split-3-2"]').count()==1)
        capture('structure')
        p.locator('[data-scene="history"]').click();ok('restore gated on viewing history',p.locator('[data-action="restore-history"]').count()==0)
        act('view-history');act('compare-history');act('restore-history');capture('history-confirm')
        ok('restore confirms new revision and execution facts','parent 为 R18' in p.inner_text('#state-dialog') and '调用 A7' in p.inner_text('#state-dialog'))
        act('confirm-restore');ok('restore creates R19 without rolling back call facts','当前版本 R19' in p.inner_text('main') and '调用 A8：取消于 R17' in p.inner_text('main'))
        ok('state lab never writes main localStorage',p.evaluate('localStorage.getItem("deck-master-v3-demo")')==mainstate)
        p.locator('#reset-sample').click();act('confirm-reset');ok('state reset never clears main localStorage',p.evaluate('localStorage.getItem("deck-master-v3-demo")')==mainstate)
        ok('no page runtime errors',not errors);ok('no external resource requests',not external)
        result['results'].append({'viewport':f'{w}x{h}','checks':checks,'count':len(checks),'page_errors':errors,'external_requests':external,'screenshots':screens})
        context.close()
    browser.close()
result['status']='passed'
result['source_unchanged']=all(hashlib.sha256((SPEC/name).read_bytes()).hexdigest()==value for name,value in inputs.items())
(HERE/'result.json').write_text(json.dumps(result,ensure_ascii=False,indent=2))
print(json.dumps({'status':result['status'],'viewports':[(x['viewport'],x['count']) for x in result['results']],'source_unchanged':result['source_unchanged']}))
